CREATE DATABASE creche;
CREATE TABLE criancas (
    id PRIMARY KEY,
    nome VARCHAR(100),
    data_nascimento DATE,
    data_matricula date,
    idade DECIMAL
);


UPDATE criancas SET nome =
SELECT * FROM criancas WHERE =
UPDATE criancas SET data_nascimento =
SELECT * FROM criancas WHERE =
UPDATE criancas SET data_matricula =
SELECT * FROM criancas WHERE =
UPDATE criancas SET idade =
SELECT * FROM criancas WHERE =
UPDATE criancas SET data_matricula =
SELECT * FROM criancas WHERE =
UPDATE criancas SET nome =
SELECT * FROM criancas WHERE =
UPDATE criancas SET sexo =
SELECT * FROM criancas WHERE =
UPDATE criancas SET idade =
SELECT * FROM criancas WHERE =
UPDATE criancas SET data_nascimento =
SELECT * FROM criancas WHERE =
UPDATE criancas SET data_matricula =
SELECT * FROM criancas WHERE =
UPDATE criancas SET sexo =
SELECT * FROM criancas WHERE =
UPDATE criancas SET nome =
SELECT * FROM criancas WHERE =
UPDATE criancas SET data_matricula =
SELECT * FROM criancas WHERE =
UPDATE criancas SET data_nascimento =
SELECT * FROM criancas WHERE =
UPDATE criancas SET idade =
SELECT * FROM criancas WHERE =
UPDATE criancas SET sexo =
SELECT * FROM criancas WHERE =
UPDATE criancas SET data_nascimento =
SELECT * FROM criancas WHERE =
UPDATE criancas SET data_matricula =
SELECT * FROM criancas WHERE =
UPDATE criancas SET idade =
SELECT * FROM criancas WHERE =
UPDATE criancas SET nome =
SELECT * FROM criancas WHERE =
UPDATE criancas SET data_matricula =
SELECT * FROM criancas WHERE =
UPDATE criancas SET data_nascimento =
SELECT * FROM criancas WHERE =
UPDATE criancas SET idade =
SELECT * FROM criancas WHERE =
UPDATE criancas SET sexo =
SELECT * FROM criancas WHERE =
UPDATE criancas SET data_matricula =
SELECT * FROM criancas WHERE =
UPDATE criancas SET data_nascimento =
SELECT * FROM criancas WHERE =
UPDATE criancas SET nome =
SELECT * FROM criancas WHERE =
UPDATE criancas SET data_matricula =
SELECT * FROM criancas WHERE =
UPDATE criancas SET sexo =
SELECT * FROM criancas WHERE =
UPDATE criancas SET idade =
SELECT * FROM criancas WHERE =
UPDATE criancas SET nome =
SELECT * FROM criancas WHERE =
UPDATE criancas SET data_matricula =
SELECT * FROM criancas WHERE =
UPDATE criancas SET data_nascimento =
SELECT * FROM criancas WHERE =
UPDATE criancas SET sexo =
SELECT * FROM criancas WHERE =
UPDATE criancas SET idade =
SELECT * FROM criancas WHERE =
UPDATE criancas SET data_matricula =
SELECT * FROM criancas WHERE =
UPDATE criancas SET data_nascimento =
SELECT * FROM criancas WHERE =
UPDATE criancas SET nome =
SELECT * FROM criancas WHERE =
UPDATE criancas SET sexo =
SELECT * FROM criancas WHERE =
UPDATE criancas SET data_matricula =
SELECT * FROM criancas WHERE =
UPDATE criancas SET nome =
SELECT * FROM criancas WHERE =
UPDATE criancas SET sexo =
SELECT * FROM criancas WHERE =
UPDATE criancas SET data_nascimento =
SELECT * FROM criancas WHERE =
UPDATE criancas SET data_matricula =
SELECT * FROM criancas WHERE =
UPDATE criancas SET sexo =
SELECT * FROM criancas WHERE =
UPDATE criancas SET data_nascimento =
SELECT * FROM criancas WHERE =
UPDATE criancas SET idade =
SELECT * FROM criancas WHERE =
UPDATE criancas SET data_matricula =
SELECT * FROM criancas WHERE =
UPDATE criancas SET nome =
SELECT * FROM criancas WHERE =
UPDATE criancas SET sexo =
SELECT * FROM criancas WHERE =
UPDATE criancas SET nome =
SELECT * FROM criancas WHERE =
UPDATE criancas SET idade =
SELECT * FROM criancas WHERE =
UPDATE criancas SET data_matricula =
SELECT * FROM criancas WHERE =
UPDATE criancas SET data_nascimento =
SELECT * FROM criancas WHERE =
UPDATE criancas SET sexo=
SELECT * FROM criancas WHERE =
UPDATE criancas SET idade =
SELECT * FROM criancas WHERE =
UPDATE criancas SET data_matricula =
SELECT * FROM criancas WHERE =
UPDATE criancas SET data_nascimento =
SELECT * FROM criancas WHERE =
UPDATE criancas SET sexo =
SELECT * FROM criancas WHERE =
UPDATE criancas SET idade =
SELECT * FROM criancas WHERE =
UPDATE criancas SET data_matricula =
SELECT * FROM criancas WHERE =
UPDATE criancas SET data_nascimento =
SELECT * FROM criancas WHERE =
UPDATE criancas SET idade =
SELECT * FROM criancas WHERE =
UPDATE criancas SET sexo =
SELECT * FROM criancas WHERE =
UPDATE criancas SET data_matricula =
SELECT * FROM criancas WHERE =
UPDATE criancas SET data_nascimento =
SELECT * FROM criancas WHERE =
UPDATE criancas SET nome =
SELECT * FROM criancas WHERE =
UPDATE criancas SET idade =
SELECT * FROM criancas WHERE =
UPDATE criancas SET sexo =
SELECT * FROM criancas WHERE =
UPDATE criancas SET data_nascimento =
SELECT * FROM criancas WHERE =
UPDATE criancas SET nome =
SELECT * FROM criancas WHERE =
UPDATE criancas SET idade =
SELECT * FROM criancas WHERE =
UPDATE criancas SET nome =
SELECT * FROM criancas WHERE =
UPDATE criancas SET data_matricula =
SELECT * FROM criancas WHERE =
UPDATE criancas SET sexo =
SELECT * FROM criancas WHERE =
UPDATE criancas SET nome =
SELECT * FROM criancas WHERE =
UPDATE criancas SET idade =
SELECT * FROM criancas WHERE =
UPDATE criancas SET data_matricula =
SELECT * FROM criancas WHERE =
UPDATE criancas SET data_nascimento =
SELECT * FROM criancas WHERE =
UPDATE criancas SET sexo =
SELECT * FROM criancas WHERE =
UPDATE criancas SET idade =
SELECT * FROM criancas WHERE =
UPDATE criancas SET nome =
SELECT * FROM criancas WHERE =
UPDATE criancas SET data_matricula =
SELECT * FROM criancas WHERE =
UPDATE criancas SET data_nascimento =
SELECT * FROM criancas WHERE =
UPDATE criancas SET idade =
SELECT * FROM criancas WHERE =
UPDATE criancas SET sexo =
SELECT * FROM criancas WHERE =
UPDATE criancas SET data_matricula =
SELECT * FROM criancas WHERE =
UPDATE criancas SET data_nascimento =
SELECT * FROM criancas WHERE =
UPDATE criancas SET nome =
SELECT * FROM criancas WHERE =
UPDATE criancas SET data_matricula =
SELECT * FROM criancas WHERE =
UPDATE criancas SET sexo =
SELECT * FROM criancas WHERE =
UPDATE criancas SET data_nascimento =
SELECT * FROM criancas WHERE =
UPDATE criancas SET nome =
SELECT * FROM criancas WHERE =
UPDATE criancas SET idade =
SELECT * FROM criancas WHERE =
UPDATE criancas SET sexo =
SELECT * FROM criancas WHERE =
UPDATE criancas SET data_matricula =
SELECT * FROM criancas WHERE =
UPDATE criancas SET data_nascimento =
SELECT * FROM criancas WHERE =
UPDATE criancas SET nome =
SELECT * FROM criancas WHERE =
UPDATE criancas SET sexo =
SELECT * FROM criancas WHERE =
UPDATE criancas SET data_matricula =
SELECT * FROM criancas WHERE =